### ISSUE TITLE
Donner la possibilité à un utilisateur de proposer un article

### ISSUE THREAD

**Issue by TuxBoy** [360WebDev/website#1]
Pour le moment seul les admin peuvent créer des articles, il faut donc donner la possibilité au utilisateur de créer leur propre articles, qui devront être validés par un admin/Modérateur.

Une possibilité de visionner l'article sur le site afin que ça soit plus facile à valider peut être sympa. Une fois la validation faite, un email ou une notification sur le site (peut être les deux) sera faite.

Au cours de la validation, ça serai sympa d'avoir une sorte de "discussion" afin d'échanger les potentiels retour entre validateur et auteur.

A compléter ici si d'autres personnes ont des idées (ou de meilleurs propositions)

**Comment by mosleymos** [comment]
Les points que tu as abordé peuvent être discutés:

> Une possibilité de visionner l'article sur le site afin que ça soit plus facile à valider peut être sympa. Une fois la validation faite, un email ou une notification sur le site (peut être les deux) sera faite.

Ce besoin se décompose en plusieurs fonctionnalités:
*  Voir un aperçu de l'article écrit
*  Enregistrer l'article
*  Valider un article par un utilisateur ayant un rôle d'admin. 
*  Envoyer un message de confirmation de publication de l'article

A l'ensemble de ses fonctionalités il me semble qu'il faudrait faire plusieurs points:
*  Ajouter un modèle qui gère le statut d'un Article. Nous aurons des modèles du genre Article et ArticleStatut. 
*  À la création d'un article par un utilisateur mettre son statut en pending. Dès qu'il est validé par un admin il passe en accepted et ce n'est que par l'envoi d'un mail qu'il passe en publié.
* Ces fonctionnalité posent aussi la question d'un brouillon d'article. Doit-on laisser l'utilisateur avoir plusieurs brouillons d'article avant publication ?


> Au cours de la validation, ça serai sympa d'avoir une sorte de "discussion" afin d'échanger les potentiels retour entre validateur et auteur.

Je pense que cet aspect n'est pas à privilegier dans un premier temps. En plus il me semble que c'est un autre issue.  Laissons les discussions dans les channels discord entre validateur et auteur 

Le fait d'ajouter un fil de discussion serait pour moi à créer dans un second temps.

**Comment by 360WebDev** [comment]
d’ailleurs, c'est plus **Proposer un article** c'est plus exacte

**Comment by TuxBoy** [comment]
J'ai mergé la première version "basique", j'ai déjà expliqué dans le trello associé.
